### ISSUE TITLE
.rds vs .csv

### ISSUE THREAD

**Issue by ben-williams** [commfish/seak_sablefish#1]
I think that maintaining the .csv structure will be beneficial as it allows for easy sharing with non R programs / people

**Comment by jysullivan** [comment]
Do you know how to maintain factor formatting in a csv? My frustration is I get the data in the format I want in 0-clean, write it as a csv, but then when I read it in I have to go through an extra hoop of defining the column class in order to keep the data structured properly.

**Comment by ben-williams** [comment]
Can convert all characters brought in with read_csv using mutate_if(is.character, factor). I think that read.csv will read in as factors (though it can be considerably slower than read_csv)
