### ISSUE TITLE
chapman m-r variance

### ISSUE THREAD

**Issue by ben-williams** [commfish/seak_sablefish#15]
https://github.com/commfish/seak_sablefish/blob/a521003c509ef0d0ac0458d25f82766644e25120/r/mark_recapture.R#L1298

Use 
M = marks released
C = fish examined for marks
R = fish caught with marks 

`var_n = ((M+1) (C+1) (M-R) (C-R)) / ((R+1)^2 (R+2))`

The CIs will then be

`ll =  Estimate - 1.965 * sqrt(var),`
`ul =  Estimate + 1.965 * sqrt(var)`

Don't worry about small sample sizes - we don't have that issue

**Comment by jysullivan** [comment]
thanks, i'm on it!

**Comment by jysullivan** [comment]
I was only using C and R form the longline survey, which explains why the abundance estimates were so high. I'm getting much more reasonable estimates now and will update the text now to include the formula I'm using for the confidence interval. 

![image](https://user-images.githubusercontent.com/7398155/54307472-a81b4280-4580-11e9-825a-ab77aacddcf1.png)

![image](https://user-images.githubusercontent.com/7398155/54307866-8ff7f300-4581-11e9-9a8d-70d15782c512.png)
