### ISSUE TITLE
Weight-at-age

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_sablefish#18]
- [X] Use predicted values from a weight-based von Bertalanffy model instead of mean weight-at-age (especially important for older ages which are poorly represented in the data
- [X] Use survey waa instead of fishery waa in the current management model instead of fishery waa because fishery waa is biased high especially at young ages - accepted by Ben and Andrew Feb 2019
- [X] Check with Dana about when and where he uses fishery and survey weight-at-age
- [ ] In past assessments the plus group (age 42+) weight-at-age was calculated as the empirical mean weight from all samples aged 42 and older. Because this estimate was influenced by outliers, we now use the predicted value for age-42 fish from the weight-based von Bertalanffy growth model used to estimate weight-at-age for all other ages. Ben: How does this differ from something like the geometric mean?

![image](https://user-images.githubusercontent.com/7398155/54375925-cfcce200-4636-11e9-8386-8d769790edbd.png)

**Comment by GreatDana** [comment]
I use the survey weight at age only (for both fishery and survey), and its
LVB by sex.

Cheers,
Dana

**Comment by jysullivan** [comment]
TMB and YPR models now use exclusively survey weight-at-age for all calculations.
