### ISSUE TITLE
Bootstrap confidence intervals for CPUE

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_sablefish#23]
@ben-williams recommended using bootstrap CIs instead of standard deviations to characterize variability in survey and fishery cpue.

e.g.
`stat_summary(fun.data = mean_cl_boot, geom = ‘smooth’)`

**Comment by jysullivan** [comment]
@ben-williams I used Ben Bolker's suggestion: https://stackoverflow.com/questions/38554383/bootstrapped-confidence-intervals-with-dplyr

The code still has the alternative figs using +/- 1 sd b/c I'm not sold on using a confidence interval. I'm really interested in characterizing the variability in the data, not so much in displaying how well the mean is estimated.

A comparison of the two methods for Fishery CPUE: 

*Top: +/- 1 sd*
![fshcpue_1997_2018](https://user-images.githubusercontent.com/7398155/54649068-92fd5280-4a5d-11e9-86a1-fe72c728029c.png)

*Bottom: 95% bootstrap CI*
![fshcpue_bootCI_1997_2018](https://user-images.githubusercontent.com/7398155/54649025-5af60f80-4a5d-11e9-877f-380ca423c457.png)

**Comment by ben-williams** [comment]
If you are trying to explore the variability in the data, that is fine, but be sure to write this up in the document as there is typically more focus on understanding the degree of certainty of an estimate. Further, I would encourage you to think about what will be the better implementation for an asa (likely inverse var?)
