### ISSUE TITLE
Review of TMB assessment

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_sablefish#38]
Comments from BW to address:

- [x] Clarify how we want to talk about recruitment and incorporating uncertainty into management in the introduction. Currently the text says,

> Finally, strong recruitment from the 2014 and possibly 2013 and 2015 year classes were reported in the Federal assessment, prompting questions about how to treat the uncertainty in recruitment for State management (Hanselman et al. 2017, Sullivan and Williams 2018). A statistical catch-at-age model coded in Template Model Builder (TMB) will allow more flexibility in exploring recruitment using random effects (Kasper et al. 2016).

- [x] Figure out which years maturity data are available from the longline survey.

We have maturity data from the survey going back to 1997 (2007 was a typo). The query for the data and assumptions about which maturity codes I associate with mature and immature are found in [`0_querynclean_data.r`](https://github.com/commfish/seak_sablefish/blob/79de094f7aeb8059eed560dee553e4b8b2fb8ea3/r/0_querynclean_data.R#L495). 

Here are the sample sizes by year:

| Year |  n |
| ------ | ---- |
|  1997| 263|
| 1998| 197|
| 1999| 156|
| 2000| 216|
| 2001| 183|
| 2002| 302|
| 2003| 391|
| 2004| 410|
| 2005| 507|
| 2006| 420|
| 2007| 429|
| 2008| 338|
| 2009| 366|
| 2010| 320|
| 2011| 365|
| 2012| 407|
| 2013| 261|
| 2014| 288|
| 2015| 292|
| 2016| 318|
| 2017| 348|
| 2018| 353|

- [x] There was a question about whether or not proportions mature-at-age were used as inputs to the model. The answer is yes, they are. The vector of proportions mature-at-age is multiplied by the female numbers-at-age matrix, female weight-at-age, and annual survivorship to time of spawning (assuming February) in order to get the [spawning biomass](https://github.com/commfish/seak_sablefish/blob/79de094f7aeb8059eed560dee553e4b8b2fb8ea3/tmb/mod.cpp#L654). 

- [x] There was a question on eqn 3 about why is this log transformed (more specifically how do I log transform 0?)
![image](https://user-images.githubusercontent.com/7398155/58117340-ce75e380-7baa-11e9-9c05-fe36f04c2584.png)
[Within the `gam` function I used the `famly = quasibinomial` argument](https://github.com/commfish/seak_sablefish/blob/79de094f7aeb8059eed560dee553e4b8b2fb8ea3/r/biological.R#L855), which allows the response variable (the proportion female observed in the survey) to be a proportion instead of the normal 0/1 response used in `family = binomial`. The default transformation for the binomial and quasibinomial distributions is `link = logit`.  The rationale for how the logit link handles 0 (or 1) observations is best explained by this Cross Validated [post](https://stats.stackexchange.com/questions/168908/how-does-the-logit-link-handle-binomial-1-0-data) (I especially like response 2). This explanation is for the binomial distribution, but the same applies for the quasibinomial, which is just a scaled version of the binomial. 

- [x] There was a question about if I have plans to incorporate additional sources of mortality

> Additional sources of mortality that are not currently included in this model include sport, subsistence and personal use harvest, estimated bycatch mortality in the halibut fishery, and estimated deadloss, which includes mortality from sand fleas, sharks, and whales.

I added some more text in this section and have added it to the long-term improvements section. To be honest I'm not sure exactly how this is normally done. Catch is fit assuming a single or time-varying selectivity curve. It's likely that adding sport and personal use harvest wouldn't affect this, but I'm not sure.

**Comment by GreatDana** [comment]
I think you mean Kristensen, not Kasper unless we are getting really
informal with citations.

**Comment by jysullivan** [comment]
Fixed, thanks @Dana!
