### ISSUE TITLE
Countbacks of marked vs unmarked fish on the longline survey

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_sablefish#39]
One major thing that is going to change in this year’s assessment is the number of fish sampled for clips/tags in the longline survey. Current methods indicate that all fish on the survey are sampled in the same way the fishery countbacks are sampled.  I found out on the survey this year this is clearly not the case. Only tagged fish are sampled, and all fish are not checked for fin clips.  I will need to change the methodology this year and analyze this mistakes’ impact on past estimates of abundance.  I am not sure how long this has been going on, but it was definitely before I started.

**Comment by ben-williams** [comment]
Can you clarify the "Only tagged fish are sampled, and all fish are not checked for fin clips". I read this as biological samples only originate from tagged fish during the ll survey. 
Unless there is a bias (e.g., only small fish are not checked for fin clips) then it is not important to check all fish for clips - a sample is fine.

**Comment by jysullivan** [comment]
Good clarification:
Tagged fish are opportunistically sampled on the longline survey. An official countback (e.g. number of marked fish out of 1000 fish) does NOT occur in the survey. This was assumed previously...

**Comment by jysullivan** [comment]
Some documentation from M. Vaughn 2019-12-19:

> We have not attempted to complete countbacks on the fish taken on this survey in a long time. This occurs for several reasons. As you have seen on the survey our crew does not handle  (or attempt to handle) every fish.  We have never observed each fish on board  and it would be a significant amount of work to have the biosampler also pick this up and complete their bio samples as well. It would also likely slow the process of crew bringing fish aboard if the bio sampler also needed to keep up with that and no one wants to make the survey day longer! 

> The best time to observe these fish would be when delivered to port. I don’t think we successfully completed a countback of all the survey fish in port more than once but I would need to research that. The problem is lack of staff available when fish come to port. On the first offload, the bulk of our staff are still on the survey. In the best case scenario that only leaves a single staff member to complete the countback and if the plant runs more than one line, we  are going to miss a lot of fish.  I know this happened one year and it was decided to halt the countback as we weren’t going to sample all fish. If you want countbacks on the survey fish, there would need to be two people exclusively available to accomplish this.

> If you have been under the impression that we have been completing the survey countbacks all these years, my guess is the data you have been looking at is based on the number of tags returned as a proxy for number of clips and the number of sablefish counted by staff at the roller. I think I remember Kristen G. referencing this as an alternative to a true countback since we struggled to successfully pull off a full countback. 

Vaughn is retiring from the Groundfish Project at the end of Dec 2019. I asked him to go through all years since 2005 to confirm that survey fish have not had a full countback. He found two years (2008 and 2010) when there *was* a full countback. There is a hard copy of these data in a binder in Sitka. Those were the only years since 2005 he could document a countback. I've added these data in data/survey/nsei_sable_llsurvey_countbacks.csv

**Comment by jysullivan** [comment]
For all old code for previous mark-recapture methods, please checkout:
[https://github.com/commfish/seak_sablefish/releases/tag/mark-recapture-pre-2019-assessment](url)

**Comment by jysullivan** [comment]
![llsrv_countback_assumptions_2005_2018](https://user-images.githubusercontent.com/7398155/71489904-81a75a80-27d4-11ea-8a17-789db90d250c.png)


Impact of this change on the M-R estimates (this figure shows 95% credible interval).
